name: flow-bench
channels:
  - conda-forge
  - defaults
  - pyrocko
dependencies:
  - python=3.11
  - matplotlib=3.6.2
  - numpy
  - pandas
  - scipy
  - obspy
  - numba
  - h5py
  - scikit-learn
  - tqdm
  - pathlib
  - requests
  - pyrocko
  - pyqt
  - openpyxl
  - ruamel.yaml
  - pyyaml
  - py7zr
